# Generated by Django 4.2 on 2025-07-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.CharField(default='Por definir', max_length=100)),
                ('profesor', models.CharField(default='Sin asignar', max_length=100)),
                ('horario', models.CharField(default='Pendiente', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad_stock', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clases',
            },
        ),
    ]
