# Generated by Django 4.2 on 2025-08-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clases',
            old_name='cantidad_stock',
            new_name='cupos',
        ),
        migrations.AlterField(
            model_name='clases',
            name='instrumento',
            field=models.CharField(choices=[('guitarra', 'Guitarra'), ('piano', 'Piano'), ('violin', 'Violín'), ('bateria', 'Batería'), ('flauta', 'Flauta'), ('otro', 'Otro')], default='otro', max_length=100),
        ),
    ]
