# Generated by Django 4.2 on 2025-07-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_ultima_actualizacion',
            new_name='fecha_ultima_modificacion',
        ),
    ]
