# Generated by Django 4.2 on 2025-07-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_fecha_ultima_actualizacion_producto_fecha_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Gestión de personas'},
        ),
    ]
