# Generated by Django 4.2 on 2025-07-21 02:33
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_options'),  # ajusta según tu última migración
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Gestión de personas',
            },
        ),
    ]